# -*- coding: utf-8 -*-
"""array operation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IteYveZGUkO3l2eaZvRWpAfpS1zdRxYk
"""

import numpy as np

lst=[1,2,3,4]
arr=np.array(lst)

type(arr)

arr.shape

lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]


arr1=np.array([lst1,lst2,lst3])

arr1.shape

#indesing

arr

arr[3]

arr[3]=5

arr

arr[1:]

arr[-1]

arr[:-1]

arr[::]

arr[::-1]

arr[::-2]

arr1

arr1[:,1]

arr1[1:,1:3]

arr1[1:,3:]

arr1[:,3:]

arr1[:,::3]

arr1[:,::4]

#EDA

arr

arr<2

arr[arr<2]

arr1.shape

arr1

arr1.reshape(5,3)

##Mechanism to create an array

np.arange(1,10,2)

np.arange(1,20,2)

np.arange(1,20,2).reshape(2,5)

np.arange(1,20,2).reshape(1,10,1)

arr*arr

arr1*2

arr1

arr1*arr1

np.ones((5,3))

np.zeros((4,5))

np.random.randint(10,50,4)

np.random.randint(10,50,4).reshape(2,2)

#normal distribution

np.random.randn(5,6)

